### ISSUE TITLE
TS13 - DeployProdução

### ISSUE THREAD

**Issue by erivanio** [labhackercd/linguagem-simples-backend#48]
Eu, como desenvolvedor, desejo configurar uma máquina remota com docker-compose de produção para ser acessada pelo frontend.

**Critérios de aceitação**
- [x] Criar docker-compose.yml de produção
- [x] Configurar nginx para servir estáticos
- [x] Configurar LetsEncrypt para acessar via https

**Comment by thiagonf** [comment]
Como foi solicitado um servidor novo sem nenhuma configuração prévia foi necessário configurar alguns pontos para que o ngnix funcione.

- https://stackoverflow.com/questions/23948527/13-permission-denied-while-connecting-to-upstreamnginx

**Comment by erivanio** [comment]
Foi solicitado acesso a máquina do elasticsearch para a funcionalidade de proxy pra o frontend

**Comment by erivanio** [comment]
A versão que usamos do letsencrypt foi atualizada, não permitindo mais a criação de novos domínios.
"In June of 2020 we will stop allowing new domains to validate via ACMEv1." --  https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430/223025
